/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecondRouteImport } from './routes/second'
import { Route as GamesRouteImport } from './routes/games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayTimestampGameIdRouteImport } from './routes/play.$timestamp.$gameId'

const SecondRoute = SecondRouteImport.update({
  id: '/second',
  path: '/second',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTimestampGameIdRoute = PlayTimestampGameIdRouteImport.update({
  id: '/play/$timestamp/$gameId',
  path: '/play/$timestamp/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/second': typeof SecondRoute
  '/play/$timestamp/$gameId': typeof PlayTimestampGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/second': typeof SecondRoute
  '/play/$timestamp/$gameId': typeof PlayTimestampGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/second': typeof SecondRoute
  '/play/$timestamp/$gameId': typeof PlayTimestampGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games' | '/second' | '/play/$timestamp/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games' | '/second' | '/play/$timestamp/$gameId'
  id: '__root__' | '/' | '/games' | '/second' | '/play/$timestamp/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRoute
  SecondRoute: typeof SecondRoute
  PlayTimestampGameIdRoute: typeof PlayTimestampGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/second': {
      id: '/second'
      path: '/second'
      fullPath: '/second'
      preLoaderRoute: typeof SecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$timestamp/$gameId': {
      id: '/play/$timestamp/$gameId'
      path: '/play/$timestamp/$gameId'
      fullPath: '/play/$timestamp/$gameId'
      preLoaderRoute: typeof PlayTimestampGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRoute,
  SecondRoute: SecondRoute,
  PlayTimestampGameIdRoute: PlayTimestampGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
