
modifiers = [
        "Crafting",
        "Gambling",
        "Survival",
        "Inventory",
        "Combat",
        "Open World",
        "Enemies",
        "Racing",
        "Shooter",
        "Puzzle",
        "Black Jack",
        "Tower Defense",
        "Bullet Hell",
        "Multiplayer",
        "Turn-based",
        "Card game",
        "Stealth",
        "Roguelike",
        "Base Building",
        "Fishing",
        "Rhythm",
        "Simulation",
        "Exploration",
        "Boss Rush",
        "Deckbuilder",
        "RPG",
        "Sports",
        "Horror",
        "Fighting",
        "Sandbox",
        "Trivia",
        "Farming",
        "Dating Sim",
        "Match-3",
        "Idle/Clicker"
]
